[book]
authors = ["Rod Conan"]
language = "en"
multilingual = false
src = "src"
title = "GMT NGAO Model with Rust DOS Actors"

[rust]
edition = "2021"

[output.html]
site-url = "/grsim-ngao/"
git-repository-url = "https://github.com/GMTO-Integrated-Modeling/grsim-ngao/tree/main/guide"
edit-url-template = "https://github.com/GMTO-Integrated-Modeling/grsim-ngao/edit/main/guide/{path}"
